### ISSUE TITLE
frontClient?

### ISSUE THREAD

**Issue by smebberson** [prismicio/nextjs-website#2]
Hi, what does the `frontClient` variable provide? Based on the code, it doesn't seem as though https://github.com/prismicio/nextjs-website/blob/master/utils/prismicHelpers.js#L20 could ever run?

This question is also asked here, https://github.com/prismicio/prismic-nextjs-sample/issues/13.

**Comment by levimykel** [comment]
Hi @smebberson, sorry for the delay. You are correct, this is not needed. I will get this fixed and push an update today.

**Comment by levimykel** [comment]
Fixed with [this commit](https://github.com/prismicio/nextjs-website/commit/5e0fe5828152a0e806f9b91654490bd0156dfaa9).

**Comment by smebberson** [comment]
@levimykel, awesome, thanks.
